version: '3'
services:

  #dnsmasq:
  #  image: vimagick/dnsmasq
  #  ports:
  #    - "53:53/tcp"
  #    - "67:67/udp"
  #  volumes:
  #    - ./dns:/etc/dnsmasq.d
  #  cap_add:
  #    - NET_ADMIN
  #  restart: always

  consul:
    command: agent -server -ui -bootstrap-expect=1 -data-dir=/var/lib/consul -node=server-1 -config-dir=/etc/consul.d -client=0.0.0.0
    image: consul:latest
    container_name: 'consul'
    volumes:
      - ./consul/server/config:/etc/consul.d
      - ./consul/server/data:/var/lib/consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8500:8500
      - 8600:8600/udp
    environment:
      SERVICE_53_IGNORE: 'yes'
      SERVICE_8300_IGNORE: 'yes'
      SERVICE_8301_IGNORE: 'yes'
      SERVICE_8302_IGNORE: 'yes'
      SERVICE_8400_IGNORE: 'yes'
      SERVICE_8500_NAME: 'consul'

  #consul-client:
  #  command: agent -config-dir=/etc/consul.d -data-dir=/var/lib/consul -node=client-1 -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul
  #  image: consul:latest
  #  container_name: 'consul-client'
  #  volumes:
  #    - ./consul/client/config:/etc/consul.d
  #    - ./consul/client/data:/var/lib/consul
  #  links:
  #    - consul


  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: 'vault'
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    links:
      - consul

  lb:
    image: camptocamp/haproxy-consul:latest
    container_name: 'lb'
    environment:
      HAPROXY_DOMAIN: '127.0.0.1.xip.io:test'
      SERVICE_80_IGNORE: 'yes'
      SERVICE_8080_NAME: 'haproxy'
    ports:
      - "80:80"
      - "8080"
    links:
      - "consul"

  # Exactly one per physical node
  #registrator:
  #  command: "-internal consul://consul:8500"
  #  image: gliderlabs/registrator:latest
  #  container_name: 'registrator'
  #  links:
  #    - "consul"
  #  volumes:
  #    - "/var/run/docker.sock:/tmp/docker.sock"
