version: '3'
services:

  dnsmasq:
   image: vimagick/dnsmasq
   ports:
    - "53:53/tcp"
    - "67:67/udp"
   volumes:
    - ./dns:/etc/dnsmasq.d
   cap_add:
    - NET_ADMIN
   restart: always

  consul:
    command: -server -bootstrap
    image: progrium/consul:latest
    container_name: 'consul'
    environment:
      SERVICE_53_IGNORE: 'yes'
      SERVICE_8300_IGNORE: 'yes'
      SERVICE_8301_IGNORE: 'yes'
      SERVICE_8302_IGNORE: 'yes'
      SERVICE_8400_IGNORE: 'yes'
      SERVICE_8500_NAME: 'consul-admin_infra'

  consul-worker:
    command: agent -retry-join=consul
    image: progrium/consul:latest
    container_name: 'consul-worker'


  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: 'vault'
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul

  lb:
    image: camptocamp/haproxy-consul:latest
    container_name: 'load-balancer'
    environment:
      HAPROXY_DOMAIN: '127.0.0.1.xip.io:test'
      SERVICE_80_IGNORE: 'yes'
      SERVICE_8080_NAME: 'proxy-admin_infra'
    ports:
      - "80:80"
      - "8080"
    links:
      - "consul"

  # Exactly one per physical node
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: 'registrator'
    links:
      - "consul"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
